require: rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
  NewCops: enable

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/ActionControllerTestCase:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - describe
    - context
    - background
    - scenario
    - namespace
    - task
    - included
    - shared_context
    - shared_examples
    - state_machine
    - configure
    - draw
    - feature
    - subject
    - let
    - let!
    - factory
    - define
    - guard
    - test

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
